identifier   = "com.tauri.repo"
product-name = "tauri-repo"
version      = "0.1.0"

[build]
before-build-command = "trunk build"
before-dev-command   = "trunk serve"
dev-url              = "http://localhost:1420"
frontend-dist        = "../dist"

[app]
with-global-tauri = true

[[app.windows]]
height = 600
title  = "tauri-repo"
width  = 800

[bundle]
active  = true
icon    = ["icons/128x128.png", "icons/128x128@2x.png", "icons/32x32.png", "icons/icon.icns", "icons/icon.ico"]
targets = "all"
